name: corda
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - alabaster=0.7.12=py_0
  - babel=2.9.0=pyhd3deb0d_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h5e8e339_1001
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py37h89c1867_1
  - cffi=1.14.4=py37h11fe52a_0
  - chardet=4.0.0=py37h89c1867_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py37h5d9358c_0
  - cudatoolkit=11.0.3=h15472ef_8
  - cycler=0.10.0=py_2
  - dbus=1.13.6=hfdff14a_1
  - docutils=0.16=py37h89c1867_3
  - expat=2.3.0=h9c3ff4c_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=hf34092f_1004
  - glib=2.66.3=h58526e2_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - icu=58.2=hf484d3e_1000
  - idna=2.10=pyh9f0ad1d_0
  - imagesize=1.2.0=py_0
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py37h2527ec5_1
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libglib=2.66.3=hbe7bbb4_0
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.41.0=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.9=h13577e0_2
  - llvm-openmp=11.1.0=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_0
  - markupsafe=1.1.1=py37h5e8e339_3
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=h58526e2_4
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - numpydoc=0.9.2=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pysocks=1.7.1=py37h89c1867_3
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.7.1=py3.7_cuda11.0.221_cudnn8.0.5_0
  - pytz=2021.1=pyhd8ed1ab_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=hf8c457e_1001
  - requests=2.25.1=pyhd3deb0d_0
  - setuptools=49.6.0=py37h89c1867_3
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.15.0=pyh9f0ad1d_0
  - snowballstemmer=2.1.0=pyhd8ed1ab_0
  - sphinx=3.5.4=pyh44b312d_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=h21135ba_1
  - torchvision=0.8.2=py37_cu110
  - tornado=6.1=py37h5e8e339_1
  - tqdm=4.42.1=py_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - absl-py==0.12.0
    - cachetools==4.2.1
    - google-auth==1.28.1
    - google-auth-oauthlib==0.4.4
    - grpcio==1.37.0
    - importlib-metadata==3.10.1
    - kornia==0.4.1
    - markdown==3.3.4
    - oauthlib==3.1.0
    - opencv-python==4.4.0.46
    - protobuf==3.15.8
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyyaml==5.3.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.1.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - werkzeug==1.0.1
    - zipp==3.4.1
